language: node_js

node_js: 14

# Always run two parallel builds: one on mac and one on linux
# the linux build will use wine to be able to build windows and
# linux apps
matrix:
  include:
    - os: linux
      sudo: required

before_install:
  - npm i -g npm@7

install:
  - npm install

script:
  - npm test

services:
  - xvfb
